=== aittiritesoufian/PPE3-CreateurMagasins/PPE3-v2-CREATEUR_UTILISATEUR/XML_DTD/utilisateurs.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT projet (utilisateurs+)>
<!ELEMENT utilisateurs (email,password?,nom,prenom)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT password (#PCDATA)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT prenom (#PCDATA)>

=== aittiritesoufian/PPE3-CreateurMagasins/PPE3-v2-CREATEUR_UTILISATEUR/XML_DTD/utilisateurs.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE projet SYSTEM "XML_DTD/utilisateurs.dtd" >
<projet>
  <utilisateurs>
    <email>soufian.a@free.fr</email>
    <password>test123</password>
    <nom>AIT TIRITE</nom>
    <prenom>SOUFIAN</prenom>
  </utilisateurs>
  <utilisateurs>
    <email>steven@gmail.com</email>
    <password>blabla123</password>
    <nom>DE CARVALHO</nom>
    <prenom>STEVEN</prenom>
  </utilisateurs>
</projet>
